### ISSUE TITLE
Is there training yaml on real denoising task?

### ISSUE THREAD

**Issue by cswry** [zhengchen1999/CAT#1]
Hello, CAT is a nice work.

There seems to be the training yaml on real denoising task missing from the code.

Could you share it?

**Comment by zhengchen1999** [comment]
Hi.
Thanks for your interest in our work. For real world denoising, the training code is built on [Restormer](https://github.com/swz30/Restormer). The training yaml is in `restormer/options/`. The training detail is in [Training](https://github.com/zhengchen1999/CAT#Training).
If you have any other problem, please let us know. Thanks.

**Comment by cswry** [comment]
OK! Thank you!
