### ISSUE TITLE
Where is test result saved?

### ISSUE THREAD

**Issue by whiteYi** [zhengchen1999/CAT#11]
I successful run the test.py, and "save_img" is true in config file. I can't find the result in "result" folder. Can you tell me where is the code to save the address of the result.

**Comment by zhengchen1999** [comment]
Here: https://github.com/zhengchen1999/CAT/blob/main/basicsr/models/sr_model.py#L172

**Comment by whiteYi** [comment]
> Here: https://github.com/zhengchen1999/CAT/blob/main/basicsr/models/sr_model.py#L172

Thanks for your reply! I find sourse about this question. Because the result address is relative path, and I moved the location of test.py so I can't find it in this project! This is a wonderful work!
