### ISSUE TITLE
Geometric self-ensemble 

### ISSUE THREAD

**Issue by joshyZhou** [zhengchen1999/CAT#2]
Hi,
Thanks for your great work! Would you like to share another version code with self-ensemble strategy, since it is mentioned in your paper.

**Comment by zhengchen1999** [comment]
Hi.
Thanks for your interest in our work. We have added the code for self-ensemble ([cat_se_model.py](https://github.com/zhengchen1999/CAT/blob/main/basicsr/models/cat_se_model.py)), and provided the test YML of CAT-R (SR, x2, x3, x4: [test_CAT_R_sr_se_x2.yml](https://github.com/zhengchen1999/CAT/blob/main/options/test/test_CAT_R_sr_se_x2.yml), [test_CAT_R_sr_se_x3.yml](https://github.com/zhengchen1999/CAT/blob/main/options/test/test_CAT_R_sr_se_x3.yml), [test_CAT_R_sr_se_x4.yml](https://github.com/zhengchen1999/CAT/blob/main/options/test/test_CAT_R_sr_se_x4.yml)). You can run the following scripts:
```
python basicsr/test.py -opt options/test/test_CAT_R_sr_se_x2.yml
python basicsr/test.py -opt options/test/test_CAT_R_sr_se_x3.yml
python basicsr/test.py -opt options/test/test_CAT_R_sr_se_x4.yml
```
If you want to test other models with self-ensemble strategy, you can modify the corresponding testing YML: `model_type: CATModle`, `selfensemble_testing: True`, similar to test_CAT_R_sr_se_x2.yml.
If you have any other problem, please let us know. Thanks.

**Comment by joshyZhou** [comment]
Thanks for your quickly reply! My problem has been solved.
