### ISSUE TITLE
关于图像输入大小问题

### ISSUE THREAD

**Issue by Chowhound-wmz** [zhengchen1999/CAT#4]
请问如果用256x256的图像输入，Cat模型的参数有没有调整的规范

**Comment by zhengchen1999** [comment]
你好，
CAT可以接受任意大小的输入图像，不用对模型参数进行调整。
另外为了便于训练，也可以将YML文件（例如：[train_CAT_A_sr_x2.yml](https://github.com/zhengchen1999/CAT/blob/main/options/train/train_CAT_A_sr_x2.yml)）中的`img_size: 64`修改为`img_size: 256`。

**Comment by Chowhound-wmz** [comment]
好的谢谢，在输入图像为256时，用Cat_unet模型进行训练需要多大显存的GPU呢，我用32G的单GPU训练似乎跑不起来

**Comment by zhengchen1999** [comment]
你好，由于CAT_Unet，在DN上的训练是按照[Restormer](https://arxiv.org/abs/2111.09881)进行设置的，所以显存需要求较多，输入图像为256，batch size/per GPU 为2时，需要69G显存。
这里可以考虑减小训练图像大小，或者batch size。此外也可以考虑降低模型本身的大小，或者将Cat_unet中的`CATB_axial` (axial-Rwin)替换为`CATB_regular` (regualr-Rwin)。

**Comment by Chowhound-wmz** [comment]
谢谢！
