### ISSUE TITLE
请问应用在三维图片上应该怎么修改mask的部分

### ISSUE THREAD

**Issue by wybAug05** [zhengchen1999/CAT#6]

**Comment by zhengchen1999** [comment]
Hi.
Thanks for your interest in our work. 

To apply CAT to 3D images, I think it is not only to modify the mask part (although the model can normally run after modifying the mask). It is also necessary to consider the three-dimensional form of Rwin-SA (about window partition). To implement these parts, you can refer to [Video Swin Transformer](https://openaccess.thecvf.com/content/CVPR2022/papers/Liu_Video_Swin_Transformer_CVPR_2022_paper.pdf), which applies (2D) Swin Transformer in 3D Video.

If you have any other problem, please let us know. Thanks.
